name: Unit Tests

on:
  push:
    branches:
      - tests-unitarios
      - tests-unitarios-RamaCompleta
      - PPTSIS
      - RamaCompleta

  pull_request:
    branches:
      - PPTSIS
      - RamaCompleta

jobs:
  backend-unit-tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm ci

      - name: Ejecutar pruebas unitarias
        run: npm test -- --run
